CY-Shop : main.o produit.o interface.o fichier.o client.o
	gcc -o CY-Shop main.o produit.o interface.o fichier.o client.o

main.o : ./Source/main.c
	gcc -o main.o -c ./Source/main.c

client.o : ./Source/client.c
	gcc -o client.o -c ./Source/client.c

fichier.o : ./Source/fichier.c
	gcc -o fichier.o -c ./Source/fichier.c

interface.o : ./Source/interface.c
	gcc -o interface.o -c ./Source/interface.c

produit.o : ./Source/produit.c
	gcc -o produit.o -c ./Source/produit.c